name: Update voxxrin

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repository
permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: update
        env:
          VOXXRIN_TOKEN: ${{ secrets.VOXXRIN_TOKEN }}
        run: |
          cd voxxrin
          chmod +x voxxrin.sh
          ./voxxrin.sh update
